// "Other" is appended separately via OTHER_OPTION with a free-text fallback.
export const COLLEGE_UNIT_OPTIONS = [
  "ACCOUNTING",
  "Administrative Office PPC",
  "Admission and Registration Services Office",
  "Admission and Registration Services Office - Admission Unit",
  "Admission and Registration Services Office - OUR",
  "Budget Office",
  "CAFES",
  "CAS",
  "Cash Office",
  "CCAS",
  "CCJE",
  "CED",
  "CET",
  "CFINS",
  "CPACD",
  "CPAM",
  "Curriculum and Instruction Office",
  "Extension Services Office",
  "Gender and Development",
  "General Service Office",
  "General Service Office Motorpool Unit",
  "GSO",
  "GSO - Preventive Maintenance of Electrical and Air-conditioning System",
  "GSO - Security Service Offices",
  "Health Services Office",
  "Holistic Development Program Office",
  "HRMDO",
  "HRMDO - Faculty and Staff Development Office",
  "ICTO",
  "Information Office",
  "Internal Audit Office",
  "Internalization and External Affairs Office",
  "National Service Training Program Office",
  "Office Of Business Affair",
  "Office of the Chief Administrative Officer - Administration",
  "Office of the Chief Administrative Officer - Finance",
  "Office of the University Board Secretary",
  "Office of the University President",
  "Office of the Vice President for Academic Affairs",
  "Office of the VP for Administration and Finance",
  "Office of the VP for Research, Innovation, Development, and Extension",
  "Office of the VP for Student Affairs and Services",
  "PLANNING OFFICE",
  "Planning Office - Insfrastructure Planning Offfice and Design Unit",
  "Procurement Office",
  "Project Development CFINS",
  "Project Management Office",
  "Publication and Printing Unit",
  "Quality Assurance Office",
  "Records Office",
  "Research Ethic Office",
  "Research, Development and Publication Office",
  "Research, Development and Publication Office - PPU",
  "Research, Development and Publication Office - TTPU",
  "Specialized Research Center Office",
  "Student Development Services Office",
  "Student Institutional Program Services Office",
  "Student Welfare Services Office",
  "Student Welfare Services Office - Guidance and Counseling Unit",
  "Supervising Administrative Officer - Administrator",
  "Supervising Administrative Officer - Finance",
  "Supply and Property Management",
  "University Legal Office",
  "University Library",
];

export const CAMPUS_OPTIONS = [
  "WPU Aborlan - Main Campus",
  "Puerto Princesa City",
  "Busuanga",
  "Culion",
  "Quezon",
  "Rio Tuba",
  "Roxas",
  "San Vicente",
  "Taytay",
];

export const AGE_GROUP_OPTIONS: string[] = [
  "Young Adult (18-25)",
  "Early Career Adult (26-35)",
  "Established Adult (36-45)",
  "Midlife Adult (46-55)",
  "Mature Adult (56-65)",
  "Senior Adult (66 and above)",
];

export const SEX_AT_BIRTH_OPTIONS: string[] = ["Male", "Female"];

export const GENDER_OPTIONS: string[] = [
  "Male",
  "Female",
  "Non-binary",
  "Agender",
  "Androgyne",
  "Bigender",
  "Genderfluid",
  "Gender Non-Conforming",
  "Genderqueer",
  "Pangender",
  "Transgender",
  "Prefer not to say",
];

export const ACADEMIC_RANK_OPTIONS: string[] = [
  "Instructor I",
  "Instructor II",
  "Instructor III",
  "Assistant Professor I",
  "Assistant Professor II",
  "Assistant Professor III",
  "Assistant Professor IV",
  "Associate Professor I",
  "Associate Professor II",
  "Associate Professor III",
  "Associate Professor IV",
  "Associate Professor V",
  "Professor I",
  "Professor II",
  "Professor III",
  "Professor IV",
  "Professor V",
  "Professor VI",
];

export const TEACHING_LOAD_OPTIONS: string[] = [
  "6 units or less",
  "7–9 units",
  "10–12 units",
  "13–15 units",
  "16–18 units",
  "19 units or more",
];

export const EMPLOYMENT_STATUS_OPTIONS: string[] = ["Permanent", "COS", "Job Order"];

export const OTHER_OPTION = "Other";
